FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    curl unzip wget gnupg \
    chromium-driver chromium

WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1
EXPOSE 5000
CMD ["python", "app.py"]
